import logging
import re
from datetime import datetime
from pathlib import Path

import yaml

logger = logging.getLogger(__name__)

_PROJECT_ROOT = Path(__file__).resolve().parent.parent


def strip_leading_frontmatter(text):
    return re.sub(r"^\s*---\s*\n.*?\n---\s*\n*", "", text or "", count=1, flags=re.DOTALL)


def _safe_filename(filename: str) -> str:
    safe = "".join(c for c in filename if c.isalnum() or c in (" ", ".", "_", "-")).rstrip()
    return safe if safe.endswith(".md") else f"{safe}.md"


class Formatter:
    """生成带 YAML frontmatter 的 Markdown 并写入目标目录。"""

    def format_markdown(self, episode, transcript_text, tags=None, processing=None):
        transcript_text = strip_leading_frontmatter(transcript_text).strip()
        frontmatter = {
            "title": episode["title"],
            "podcast": episode["podcast_name"],
            "date": episode["published"],
            "duration": episode["duration"],
            "link": episode["audio_url"],
            "source_link": episode["link"],
            "tags": tags or [],
            "processed_at": datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        }
        if processing:
            frontmatter.update(processing)

        yaml_str = yaml.dump(frontmatter, allow_unicode=True, default_flow_style=False)
        return f"---\n{yaml_str}---\n\n{transcript_text}\n\n---\n*Generated by Read Podcast*\n"

    def save_note(self, content, filename, target_dir, podcast_name=None):
        """写入 target_dir；权限失败时降级到 workspace 备份目录。"""
        safe_filename = _safe_filename(filename)
        target_path = Path(target_dir) / safe_filename
        try:
            target_path.parent.mkdir(parents=True, exist_ok=True)
            target_path.write_text(content, encoding="utf-8")
            return str(target_path)
        except (PermissionError, OSError) as exc:
            fallback_dir = _PROJECT_ROOT / "workspace" / (podcast_name or "unknown") / "markdown"
            fallback_dir.mkdir(parents=True, exist_ok=True)
            fallback_path = fallback_dir / safe_filename
            logger.warning("写入 %s 失败 (%s)，已降级保存到 %s", target_path, exc, fallback_path)
            fallback_path.write_text(content, encoding="utf-8")
            return str(fallback_path)
