/**
 * 稿件 Markdown 格式化（行为迁移自 mac_worker/core/formatter.py，Edge 独立维护）。
 *
 * 产出带 YAML frontmatter 的正式稿。刻意不引入 YAML 库：使用轻量确定性字符串生成，
 * 保证 Workflows Free CPU 约束下也可完成（O(n) 扫描 + 拼接）。
 */
import { EDGE_LOCAL_TIME_ZONE } from "./defaults";

export interface FormatterEpisode {
  title: string;
  podcast_name: string;
  published: string;
  duration: string;
  audio_url: string;
  link: string;
}

const YAML_SPECIAL_START = /^[-?:,[\]{}#&*!|>'"%@`]/;
const YAML_INLINE_SPECIALS = /[,[\]{}#&*!|>'"%@`]/;
const YAML_RESERVED = /^(?:true|false|yes|no|on|off|null|~)$/i;
const YAML_NUMBERLIKE = /^[+-]?(?:\d+\.?\d*|\.\d+)(?:[eE][+-]?\d+)?$/;
const YAML_INTLIKE = /^[+-]?\d+$/;
const YAML_DATELIKE = /^\d{4}-\d{2}-\d{2}(?:[Tt ].*)?$/;

export function stripLeadingFrontmatter(text: string): string {
  return (text ?? "").replace(/^\s*---\s*\n[\s\S]*?\n---\s*\n*/, "");
}

/** 与 PyYAML 消费端兼容的标量输出：安全串保持裸写，其余加引号。 */
function yamlString(value: string): string {
  if (value === "") return '""';
  if (/[\x00-\x1f\x7f]/.test(value)) return JSON.stringify(value);
  if (isPlainSafe(value)) return value;
  return `'${value.replace(/'/g, "''")}'`;
}

function isPlainSafe(value: string): boolean {
  if (value !== value.trim()) return false;
  if (YAML_SPECIAL_START.test(value)) return false;
  if (YAML_INLINE_SPECIALS.test(value)) return false;
  if (/:(\s|$)/.test(value)) return false;
  if (/\s#/.test(value)) return false;
  if (YAML_RESERVED.test(value)) return false;
  if (YAML_NUMBERLIKE.test(value)) return false;
  if (YAML_INTLIKE.test(value)) return false;
  if (YAML_DATELIKE.test(value)) return false;
  return true;
}

function yamlValue(value: unknown): string {
  if (typeof value === "boolean") return value ? "true" : "false";
  if (typeof value === "number" && Number.isFinite(value)) return String(value);
  if (value === null || value === undefined) return "null";
  return yamlString(String(value));
}

/** 部署可选的 MANUSCRIPT_TIME_ZONE（IANA 时区名）；缺省或无效时回退 EDGE_LOCAL_TIME_ZONE。 */
export function manuscriptTimeZone(value: string | undefined): string {
  const zone = (value ?? "").trim();
  if (!zone) return EDGE_LOCAL_TIME_ZONE;
  try {
    new Intl.DateTimeFormat("en-CA", { timeZone: zone });
    return zone;
  } catch {
    console.warn(`Invalid MANUSCRIPT_TIME_ZONE '${zone}', falling back to ${EDGE_LOCAL_TIME_ZONE}`);
    return EDGE_LOCAL_TIME_ZONE;
  }
}

/** 沿用原生实现的本地时区语义，输出 `YYYY-MM-DD HH:MM:SS`。 */
export function formatLocalTimestamp(now: Date, timeZone = EDGE_LOCAL_TIME_ZONE): string {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hourCycle: "h23",
  }).formatToParts(now);
  const pick = (type: string) => parts.find(part => part.type === type)?.value ?? "00";
  return `${pick("year")}-${pick("month")}-${pick("day")} ${pick("hour")}:${pick("minute")}:${pick("second")}`;
}

/**
 * 生成带 YAML frontmatter 的正式稿。
 * frontmatter 固定包含：title / podcast / date / duration / link / source_link / tags /
 * processed_at，以及 processing 追加字段（refinement_success、transcript_source）。
 */
export function formatMarkdown(
  episode: FormatterEpisode,
  transcriptText: string,
  tags: string[] = [],
  processing: Record<string, string | boolean> | null = null,
  now: Date = new Date(),
  timeZone: string = EDGE_LOCAL_TIME_ZONE,
): string {
  const body = stripLeadingFrontmatter(transcriptText).trim();
  const lines: string[] = [];
  lines.push(`title: ${yamlString(episode.title ?? "")}`);
  lines.push(`podcast: ${yamlString(episode.podcast_name ?? "")}`);
  lines.push(`date: ${yamlString(episode.published ?? "")}`);
  lines.push(`duration: ${yamlString(episode.duration ?? "")}`);
  lines.push(`link: ${yamlString(episode.audio_url ?? "")}`);
  lines.push(`source_link: ${yamlString(episode.link ?? "")}`);
  if (!tags.length) {
    lines.push("tags: []");
  } else {
    lines.push("tags:");
    for (const tag of tags) lines.push(`- ${yamlString(tag)}`);
  }
  lines.push(`processed_at: ${yamlString(formatLocalTimestamp(now, timeZone))}`);
  if (processing) {
    for (const [key, value] of Object.entries(processing)) {
      lines.push(`${key}: ${yamlValue(value)}`);
    }
  }
  return `---\n${lines.join("\n")}\n---\n\n${body}\n\n---\n*Generated by Read Podcast*\n`;
}
